server:
  port: 8091
  servlet:
    context-path: /

logging:
  config: classpath:log4j2.xml

  mail:
    host: "smtp.qq.com"
    username: "xxx"
    password: "xxx"
test:
  mail:
    send:
    cc:

#定时任务配置
#'index.job': '0 0 0 * * ?'
#'thirdOrderCancel.job': '0 0/60 * * * ?'
'autoRefund.job': '0 0/60  * * * ?'
#'deleteCosUploadImg.job': '0 0 * * * ?'

